# Generated by Django 4.2.2 on 2023-07-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements14', '0002_advertisements14_connection'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements14',
            table='advertisements',
        ),
    ]
