# Generated by Django 4.2.2 on 2023-08-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements14', '0004_advertisements14_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements14',
            name='image',
            field=models.ImageField(default='', upload_to='advertisements/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
