# Generated by Django 4.2.2 on 2023-07-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements14', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements14',
            name='connection',
            field=models.BooleanField(default=True, help_text='Отметьте, возможна ли связь с продавцом', verbose_name='связь'),
        ),
    ]
